version: "3.7"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV_MODE=true
    network_mode: host
    volumes:
      - .:/app
    command: [ "gow", "run", "." ]
    depends_on:
      - postgres
      - migrate

  postgres:
    image: postgres:12
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msmc-auth-service
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    network_mode: host
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@localhost:5432/msmc-auth-service?sslmode=disable", "up" ]
    depends_on:
      - postgres

volumes:
  postgres-data: