// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/server": {
            "get": {
                "description": "Get all servers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "Get all servers",
                "operationId": "get-all-servers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/shared.ServerInstanceStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "shared.MinecraftEngine": {
            "type": "string",
            "enum": [
                "vanilla",
                "forge"
            ],
            "x-enum-varnames": [
                "VanillaEngine",
                "ForgeEngine"
            ]
        },
        "shared.ServerInstance": {
            "type": "object",
            "properties": {
                "docker_id": {
                    "type": "string"
                },
                "engine": {
                    "$ref": "#/definitions/shared.MinecraftEngine"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "seed": {
                    "type": "string"
                }
            }
        },
        "shared.ServerInstanceStatus": {
            "type": "object",
            "properties": {
                "running": {
                    "type": "boolean"
                },
                "server_instance": {
                    "$ref": "#/definitions/shared.ServerInstance"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MSMC API",
	Description:      "This is MSMC API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
