basePath: /
definitions:
  internal.TokenResponse:
    properties:
      token:
        type: string
    type: object
  internal.userInfoDto:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: This is the auth server for MSMC
  title: MSMC auth API
  version: "0.1"
paths:
  /get-user-info:
    post:
      consumes:
      - application/json
      description: Get user info
      parameters:
      - description: ID
        in: body
        name: id
        schema:
          type: integer
      - description: Email
        in: body
        name: email
        schema:
          type: string
      - description: Username
        in: body
        name: username
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.userInfoDto'
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Get user info
  /login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Email
        in: body
        name: email
        schema:
          type: string
      - description: Username
        in: body
        name: username
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.TokenResponse'
      summary: Login a user
  /login-remote:
    post:
      consumes:
      - application/json
      description: Login a user to remote server
      parameters:
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: string
      - description: URL
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.TokenResponse'
      summary: Login a user remotely
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              token:
                type: string
            type: object
      summary: Register a new user
swagger: "2.0"
